#!/bin/sh


if [ "$FILES" != "" ]
then
    echo "Running Code Sniffer. Code standard PSR12."
    ./vendor/bin/phpcs --standard=PSR12 --encoding=utf-8 -n -p $FILES
    if [ $? != 0 ]
    then
        echo "Fix the error before commit!"
        echo "Run"
        echo "  ./vendor/bin/phpcbf $FILES"
        echo "for automatic fix or fix it manually."
        exit 1
    fi
fi
